modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "ARR"

[[mods]]
modId = "badgebox"
version = "${version}"
displayName = "Badge Box"
authors = "Linguardium and maste"
description = '''
Adds Badges and a Badge Box for Cobblemon
'''
#logoFile = ""

[[dependencies.badgebox]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.badgebox]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.badgebox]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "badgebox.mixins.json"
